/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    careers: Career;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'blog-page': BlogPage;
    'careers-page': CareersPage;
    homepage: Homepage;
    'site-labels': SiteLabel;
    'site-branding': SiteBranding;
    'features-content': FeaturesContent;
    'testimonials-content': TestimonialsContent;
    'faq-content': FaqContent;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    'careers-page': CareersPageSelect<false> | CareersPageSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-labels': SiteLabelsSelect<false> | SiteLabelsSelect<true>;
    'site-branding': SiteBrandingSelect<false> | SiteBrandingSelect<true>;
    'features-content': FeaturesContentSelect<false> | FeaturesContentSelect<true>;
    'testimonials-content': TestimonialsContentSelect<false> | TestimonialsContentSelect<true>;
    'faq-content': FaqContentSelect<false> | FaqContentSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  avatar?: (number | null) | Media;
  designation?: string | null;
  bio?: string | null;
  social?: {
    twitter?: string | null;
    linkedin?: string | null;
    github?: string | null;
    website?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  subTitle?: string | null;
  /**
   * Short summary for blog listings. Auto-generated from content if empty.
   */
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  author: number | User;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tags?: string[] | null;
  status: 'draft' | 'scheduled' | 'published';
  /**
   * Scheduled: set future date. Published: auto-set to now if empty.
   */
  publishedAt?: string | null;
  seo?: {
    /**
     * Override the page title for search engines. Defaults to post title.
     */
    title?: string | null;
    /**
     * Override the meta description. Defaults to excerpt.
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  slug: string;
  department: 'cybersecurity' | 'data-services' | 'engineering' | 'operations' | 'sales-marketing';
  /**
   * e.g., Remote, New York, NY, or Hybrid - San Francisco
   */
  location: string;
  type: 'full-time' | 'part-time' | 'contract' | 'internship';
  experienceLevel: 'entry' | 'mid' | 'senior' | 'lead';
  remoteOption: 'remote' | 'onsite' | 'hybrid';
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  responsibilities: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  requirements: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional qualifications or skills
   */
  niceToHave?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Mark this position to appear in the featured jobs section
   */
  featured?: boolean | null;
  clearanceRequired?: boolean | null;
  /**
   * e.g., Secret, Top Secret, etc.
   */
  clearanceDetails?: string | null;
  salary: {
    type: 'range' | 'fixed' | 'competitive';
    currency?: ('USD' | 'EUR' | 'GBP' | 'INR') | null;
    /**
     * Minimum salary amount
     */
    min?: number | null;
    /**
     * Maximum salary amount
     */
    max?: number | null;
    /**
     * Fixed salary amount
     */
    amount?: number | null;
  };
  status: 'draft' | 'scheduled' | 'published' | 'closed';
  /**
   * Scheduled: set future date. Published: auto-set to now if empty.
   */
  publishedAt?: string | null;
  seo?: {
    /**
     * Override the page title for search engines. Defaults to job title.
     */
    title?: string | null;
    /**
     * Override the meta description.
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  designation?: T;
  bio?: T;
  social?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        github?: T;
        website?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subTitle?: T;
  excerpt?: T;
  featuredImage?: T;
  author?: T;
  content?: T;
  tags?: T;
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  department?: T;
  location?: T;
  type?: T;
  experienceLevel?: T;
  remoteOption?: T;
  description?: T;
  responsibilities?: T;
  requirements?: T;
  niceToHave?: T;
  featured?: T;
  clearanceRequired?: T;
  clearanceDetails?: T;
  salary?:
    | T
    | {
        type?: T;
        currency?: T;
        min?: T;
        max?: T;
        amount?: T;
      };
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage blog page headings, descriptions, and empty states
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  /**
   * Main heading displayed at the top of the blog page
   */
  heading: string;
  /**
   * Subheading text below the main heading
   */
  description: string;
  /**
   * Title shown when there are no published posts
   */
  emptyStateTitle: string;
  /**
   * Description shown when there are no published posts
   */
  emptyStateDescription: string;
  /**
   * Text for the "read more" link on each blog post card
   */
  ctaText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage careers page headings, descriptions, and empty states
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page".
 */
export interface CareersPage {
  id: number;
  /**
   * Main heading displayed at the top of the careers page
   */
  heading: string;
  /**
   * Subheading text below the main heading
   */
  description: string;
  /**
   * Title shown when there are no open positions
   */
  emptyStateTitle: string;
  /**
   * Description shown when there are no open positions
   */
  emptyStateDescription: string;
  /**
   * Text for the "view details" link on each career card
   */
  ctaText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage homepage hero section and welcome messages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Main heading shown on the homepage
   */
  heroHeading: string;
  /**
   * Subheading text below the main hero heading
   */
  heroSubheading: string;
  /**
   * Text for the primary CTA button
   */
  heroPrimaryButtonText: string;
  /**
   * Link for the primary CTA button
   */
  heroPrimaryButtonLink?: string | null;
  /**
   * Text for the secondary CTA button
   */
  heroSecondaryButtonText: string;
  /**
   * Link for the secondary CTA button
   */
  heroSecondaryButtonLink?: string | null;
  /**
   * Greeting text shown to logged-in users (email will be appended automatically)
   */
  loggedInGreeting: string;
  /**
   * Choose between waitlist email capture or pricing display
   */
  ctaType: 'waitlist' | 'pricing';
  /**
   * Main heading for the CTA section
   */
  ctaHeading: string;
  /**
   * Description text for the CTA section
   */
  ctaDescription: string;
  /**
   * Placeholder text for the email input (Waitlist CTA only)
   */
  waitlistEmailPlaceholder?: string | null;
  /**
   * Button text for waitlist submission (Waitlist CTA only)
   */
  waitlistButtonText?: string | null;
  /**
   * Name of the pricing plan (Pricing CTA only)
   */
  pricingPlanName?: string | null;
  /**
   * Price display (e.g., "$29/mo" or "$299/yr")
   */
  pricingPrice?: string | null;
  /**
   * Subtext below the price
   */
  pricingPriceSubtext?: string | null;
  /**
   * List of features included in the plan
   */
  pricingFeatures?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Button text for pricing CTA (Pricing CTA only)
   */
  pricingButtonText?: string | null;
  /**
   * URL for the pricing CTA button
   */
  pricingButtonLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage reusable labels, button text, and fallback messages used throughout the site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-labels".
 */
export interface SiteLabel {
  id: number;
  /**
   * Generic "read more" link text
   */
  readMore: string;
  /**
   * Generic "learn more" link text
   */
  learnMore: string;
  /**
   * Loading state text
   */
  loading: string;
  /**
   * Generic "view details" link text
   */
  viewDetails: string;
  /**
   * Default author name when author is missing
   */
  authorFallback: string;
  /**
   * Message shown when blog post has no excerpt
   */
  noExcerptFallback: string;
  /**
   * Alt text for placeholder images
   */
  noImageFallback: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage your site logo and branding assets
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-branding".
 */
export interface SiteBranding {
  id: number;
  /**
   * Font Awesome brand icon name (e.g., "react", "apple", "google", "stripe"). Find icons at fontawesome.com/icons
   */
  logoIcon: string;
  /**
   * Text to display next to the logo icon
   */
  logoText: string;
  /**
   * Full company name for metadata and copyright
   */
  companyName: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the features section content on your landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features-content".
 */
export interface FeaturesContent {
  id: number;
  /**
   * Main heading for the features section
   */
  heading: string;
  /**
   * Subheading text below the main heading
   */
  subheading: string;
  /**
   * List of features to display (3-6 features recommended)
   */
  features: {
    /**
     * Title of the feature
     */
    title: string;
    /**
     * Brief description of the feature
     */
    description: string;
    /**
     * Choose the SVG illustration style for this feature
     */
    illustration: 'lightning' | 'shield' | 'layers' | 'branches' | 'sparkles' | 'rocket';
    /**
     * Icon to display in the badge (Lucide icon name)
     */
    icon:
      | 'Zap'
      | 'Shield'
      | 'Layers'
      | 'GitBranch'
      | 'Sparkles'
      | 'Rocket'
      | 'Lock'
      | 'Database'
      | 'Cloud'
      | 'Code'
      | 'Globe'
      | 'Settings';
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage testimonials displayed on your website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-content".
 */
export interface TestimonialsContent {
  id: number;
  /**
   * Main heading for the testimonials section
   */
  heading: string;
  /**
   * Subheading text below the main heading
   */
  subheading?: string | null;
  /**
   * List of customer testimonials
   */
  testimonials: {
    name: string;
    role: string;
    company: string;
    content: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage frequently asked questions on your website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-content".
 */
export interface FaqContent {
  id: number;
  /**
   * Main heading for the FAQ section
   */
  heading: string;
  /**
   * Subheading text below the main heading
   */
  subheading?: string | null;
  /**
   * List of frequently asked questions and answers
   */
  faqs: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage contact page content and information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  /**
   * Main heading shown at the top of the contact page
   */
  heading: string;
  /**
   * Subheading text below the main heading
   */
  subheading: string;
  /**
   * Primary contact email address
   */
  email: string;
  /**
   * Description text for the email section
   */
  emailDescription?: string | null;
  /**
   * Physical office address
   */
  officeAddress: string;
  /**
   * Description text for the office section
   */
  officeDescription?: string | null;
  /**
   * List of contact phone numbers
   */
  phoneNumbers: {
    number: string;
    id?: string | null;
  }[];
  /**
   * Description text for the phone section
   */
  phoneDescription?: string | null;
  /**
   * Heading for the social media section
   */
  socialHeading: string;
  /**
   * List of social media profiles
   */
  socialLinks?:
    | {
        platform: string;
        url: string;
        icon: 'github' | 'twitter' | 'linkedin' | 'instagram' | 'facebook' | 'youtube' | 'discord' | 'slack';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  emptyStateTitle?: T;
  emptyStateDescription?: T;
  ctaText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page_select".
 */
export interface CareersPageSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  emptyStateTitle?: T;
  emptyStateDescription?: T;
  ctaText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroHeading?: T;
  heroSubheading?: T;
  heroPrimaryButtonText?: T;
  heroPrimaryButtonLink?: T;
  heroSecondaryButtonText?: T;
  heroSecondaryButtonLink?: T;
  loggedInGreeting?: T;
  ctaType?: T;
  ctaHeading?: T;
  ctaDescription?: T;
  waitlistEmailPlaceholder?: T;
  waitlistButtonText?: T;
  pricingPlanName?: T;
  pricingPrice?: T;
  pricingPriceSubtext?: T;
  pricingFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  pricingButtonText?: T;
  pricingButtonLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-labels_select".
 */
export interface SiteLabelsSelect<T extends boolean = true> {
  readMore?: T;
  learnMore?: T;
  loading?: T;
  viewDetails?: T;
  authorFallback?: T;
  noExcerptFallback?: T;
  noImageFallback?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-branding_select".
 */
export interface SiteBrandingSelect<T extends boolean = true> {
  logoIcon?: T;
  logoText?: T;
  companyName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features-content_select".
 */
export interface FeaturesContentSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        illustration?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-content_select".
 */
export interface TestimonialsContentSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  testimonials?:
    | T
    | {
        name?: T;
        role?: T;
        company?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-content_select".
 */
export interface FaqContentSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  email?: T;
  emailDescription?: T;
  officeAddress?: T;
  officeDescription?: T;
  phoneNumbers?:
    | T
    | {
        number?: T;
        id?: T;
      };
  phoneDescription?: T;
  socialHeading?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}